name: CI

on:
  push:
    branches: [master, main]
    paths:
      - ./prisma/migrations/**
  pull_request:
    branches: [master, main]
    paths:
      - ./prisma/migrations/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/finia-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --quiet --legacy-peer-deps

      - name: Install OpenSSL and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1

      - name: Build the project
        run: npm run build:prod

      - name: Print environment variables
        run: printenv

      - name: Run Tests
        run: npm run test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
