name: Run Action

on:
  push:
    branches: [master, main]
    paths:
      - ./prisma/migrations/**
  pull_request:
    branches: [master, main]
    paths:
      - ./prisma/migrations/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      cockroach:
        image: cockroachdb/cockroach:v22.1.10
        ports:
          - 26257:26257
        env:
          COCKROACH_USER: root
          COCKROACH_DATABASE: testdb
        options: >-
          --entrypoint=/bin/bash
          --health-cmd="cockroach sql --insecure -e 'SELECT 1;'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --quiet --legacy-peer-deps

      - name: Install OpenSSL and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1

      - name: Download CA Cert
        run: |
          mkdir -p $HOME/.postgresql/
          curl --create-dirs -o $HOME/.postgresql/root.crt '${{ secrets.COCKROACHDB_CERT_URL }}'

      - name: Build the project
        run: npm run build

      - name: Run Tests (Local, Insecure)
        run: npm run test
        env:
          DATABASE_URL: postgresql://root@localhost:26257/testdb?sslmode=disable

      - name: Deploy Database Schema (Secure)
        run: npm run db:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SSL_CERT_FILE: $HOME/.postgresql/root.crt

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
