name: Run Action

on:
  push:
    branches: [master, main]
    paths:
      - ./prisma/migrations/**
  pull_request:
    branches: [master, main]
    paths:
      - ./prisma/migrations/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --quiet --legacy-peer-deps

      - name: Install OpenSSL
        run: |
          apt-get update
          apt-get install -y libssl1.1

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm run test
        env:
          DATABASE_URL: ${{secrets.DATABASE_DEV_URL}}

      - name: Deploy Database Schema
        run: npm run db:deploy
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
